### ISSUE TITLE
TypeError: a bytes-like object is required, not 'str'

### ISSUE THREAD

**Issue by mokman** [geigerzaehler/beets-check#31] opened 2019-08-11 09:23 UTC
everytime i get to check a corrupted flac this is the outcome:

Traceback (most recent call last):               
  File "/usr/bin/beet", line 11, in <module>
    load_entry_point('beets==1.4.9', 'console_scripts', 'beet')()
  File "/usr/lib/python3.7/site-packages/beets/ui/__init__.py", line 1266, in main
    _raw_main(args)
  File "/usr/lib/python3.7/site-packages/beets/ui/__init__.py", line 1253, in _raw_main
    subcommand.func(lib, suboptions, subargs)
  File "/usr/lib/python3.7/site-packages/beetsplug/check.py", line 231, in func
    self.check(checksums=options.checksums)
  File "/usr/lib/python3.7/site-packages/beetsplug/check.py", line 277, in check
    self.execute_with_progress(check, items, msg)
  File "/usr/lib/python3.7/site-packages/beetsplug/check.py", line 391, in execute_with_progress
    for _ in e.map(func, args):
  File "/usr/lib/python3.7/concurrent/futures/_base.py", line 598, in result_iterator
    yield fs.pop().result()
  File "/usr/lib/python3.7/concurrent/futures/_base.py", line 428, in result
    return self.__get_result()
  File "/usr/lib/python3.7/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
  File "/usr/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/lib/python3.7/site-packages/beetsplug/check.py", line 259, in check
    verify_integrity(item)
  File "/usr/lib/python3.7/site-packages/beetsplug/check.py", line 58, in verify_integrity
    checker.run(item)
  File "/usr/lib/python3.7/site-packages/beetsplug/check.py", line 450, in run
    self.parse(stdout, stderr, process.returncode, item.path)
  File "/usr/lib/python3.7/site-packages/beetsplug/check.py", line 491, in parse
    for line in stderr.split('\n'):
TypeError: a bytes-like object is required, not 'str'

what could it mean?

**Comment by geigerzaehler** [comment] 2019-08-12 10:02
Thanks for the report @mokman. This is a duplicate of #28. The error is due to a lack of Python 3 support. This was fixed in #32. Please install the new version.

**Closed** 2019-08-12 10:02 UTC
